### ISSUE TITLE
Support for netmasks other than /24

### ISSUE THREAD

**Issue by kecorbin** [kecorbin/acimigrate#1]
XML API in NX-OS doesn't make mask easy to derive from.  Need to support masking.

**Comment by chapeter** [comment]
Need to pull Ip addresses into migration_dict for this comparison.  Suggest using "show ip address" as it shows netmask and all secondary IP's by IP subnet:
Vlan123, Interface status: protocol-down/link-down/admin-down, iod: 3,
  IP address: 3.3.3.3, IP subnet: 3.3.3.0/24
  IP address: 1.1.1.2, IP subnet: 1.1.1.0/24 secondary
  IP address: 2.2.2.2, IP subnet: 2.2.2.0/25 secondary


Then something like this:
    import ipaddress
    vip = u'3.3.3.1'
    svi = u'3.3.3.0/25'
    ipaddress.ip_address(vip) in ipaddress.ip_network(svi)

**Comment by kecorbin** [comment]
this is breaking something. 

ERROR:acimigrate:Exception on /migrate [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/acimigrate/views.py", line 70, in domigrate
    result = migrate(nexus, apic, auto=True, layer3=l3)
  File "/usr/src/app/acimigrate/tasks.py", line 30, in migrate
    subnet = unicode(hsrp['subnets'][count]+"/"+str(hsrp['masks'][count]))
IndexError: list index out of range
